name: 部署 Rspress 网站至静态页面

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
          cache: true

      - name: 配置页面
        uses: actions/configure-pages@v5

      - name: 下载依赖项
        run: pnpm install
      - name: 使用 Rspress 构建页面
        run: |
          pnpm run build

      - name: 上传资源文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc_build

  # 部署页面
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: 部署
    steps:
      - name: 部署至 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4